name: Android CI

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give gradlew permission
        run: chmod +x ./gradlew || true

      - name: Build APK (Debug)
        run: ./gradlew assembleDebug

      - name: Build AAB (Release)
        run: ./gradlew bundleRelease || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: solver-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: solver-release-aab
          path: app/build/outputs/bundle/release/*.aab
